version: '3'

# Networks
networks:
  default:
    external:
      name: metamarket_default

# Services
services:
  # PHP My Admin
  pma-service:
    image: phpmyadmin:5.1.3
    container_name: c-pma
    hostname: pma
    networks:
      - default
    ports:
      - 8080:80
    restart: always
    environment:
      - PMA_ARBITRARY=1

  # PHP FPM
  php-service:
    image: php:8.1.4-fpm
    container_name: c-php
    hostname: php
    networks:
      - default
    volumes:
      - ./src:/src

  # Apache
  apache-service:
    image: httpd:2.4.53
    container_name: c-httpd
    networks:
      - default
    volumes:
      - ./src:/src
      - ../docker-configs/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-service
